# Analysis of specific junction

We are exemplary considering junction CIRMBUYJFK_f__CWCCKOQCWZ_r

In [1]:
# set working directory to project folder
import sys, os, re
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.graph_objects as go

import mplcursors

import altair as alt
from itertools import combinations
import numpy as np
import pypangraph as pp
from Bio import Phylo, SeqIO, AlignIO, Align
from Bio.Align import AlignInfo
from Bio.motifs import Motif
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord

import plotly.io as pio
pio.renderers.default = "browser" 


from pathlib import Path
import subprocess

from Bio.Phylo.TreeConstruction import DistanceCalculator
from scipy.cluster.hierarchy import linkage, dendrogram, fcluster
from scipy.spatial.distance import squareform

from junction_analysis.helpers import get_tree_order, convert_gbk_fasta, convert_gbk_fasta_plasmids
import junction_analysis.pangraph_utils as pu
from junction_analysis.plotting import plot_junction_pangraph_combined, plot_junction_pangraph_interactive, plot_dendrogram
from junction_analysis.consensus import find_consensus_paths, make_deduplicated_paths
from junction_analysis.block_alignment import create_block_msas, summarize_block_msas, analyze_alignment, cluster_alignment, retrieve_cluster_assignments
from junction_analysis.junction_trees import build_tree_from_block_list

from junction_analysis.annotate_insertions import write_insertions_fasta, get_insertions_deletions_from_consensus, retrieve_SAMids_txt, combine_NCBI_atb_results, load_all_deletions_summaries, summarize_deletions_consensus, find_insertion_hits_own_genome, find_insertion_hits_in_plasmids, load_all_insertions_summaries

In [2]:
example_junction = "CIRMBUYJFK_f__CWCCKOQCWZ_r"
example_pangraph = pp.Pangraph.from_json(f"../results/junction_pangraphs/{example_junction}.json")

aln_path = f"../results/block_alignments/{example_junction}/block_11400043001338627984_aln.fa"
distance_matrix, Z, names = cluster_alignment(aln_path)
clusters = retrieve_cluster_assignments(Z, names, n_clusters=2)

## Analyze deviations (insertions / deletions) from consensus path
Consider the two consensus paths seperately from each other.

In [3]:
# choosing higher thresholds merges the two consensus paths into one, however this might not be possible for all junctions while still keeping all desired consensus paths
consensus_paths, path_dict, deduplicated_blog_freq, similarity_matrix, assignment_df = find_consensus_paths(example_pangraph, rare_block_threshold=10, rare_edge_threshold=10, min_n_isolates_per_consensus=5)
plot_junction_pangraph_interactive(
    example_pangraph,
    show_consensus=True,
    consensus_paths=consensus_paths,
    assignments=assignment_df,
    order="tree",
    cluster_map=clusters,
    title = "Junction Block Structure with 2 Clusters"
)

Found 2 unique paths.

### Consensus 2

In [4]:
insertions_2, deletions_2, inversions_2 = get_insertions_deletions_from_consensus(assignment_df, consensus_paths, path_dict, consensus = 2)
insertions_df_2 = write_insertions_fasta(example_junction, example_pangraph, insertions_2, consensus = 2, save_df=True)

# upload fastas: scp -r /Users/mariebecker/Documents/Uni/ETH/Masterarbeit/marie-junctions/results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus2 becker0010@transfer12.scicore.unibas.ch:/scicore/home/neher/GROUP/data/2025_all_the_bacteria/lexicmap_index/queries/CIRMBUYJFK_f__CWCCKOQCWZ_r/
# run:  bash run_all_lexicmap.sh ./queries/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus2 on cluster
# download results:  scp -r becker0010@transfer12.scicore.unibas.ch:'/scicore/home/neher/GROUP/data/2025_all_the_bacteria/lexicmap_index/queries/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus2/*.lexicmap.tsv' /Users/mariebecker/Documents/Uni/ETH/Masterarbeit/marie-junctions/results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus2/

Insertions:
NZ_AP022171.1 INSERTED: [18228278273347143766|+|]
NZ_CP098219.1 INSERTED: [2278011600046483881|+|]

In [9]:
# retrieve SAM... ids for NCBI lookup
retrieve_SAMids_txt(parent_dir="../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus2")

# to lookup in NCBI run from results/atb_lookup: bash fetch_biosamples_consensus.sh CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1

In [10]:
combine_NCBI_atb_results(parent_dir="../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus2")

In [11]:
# not annotated as insertion sequence but this is gene content annotation:
#NZ_AP022171.1	GenBank	gene	10173	10694	.	+	.	ID=H7R27_RS10275;Name=ugpC;gene=ugpC;is_partial=False;locus_tag=H7R27_RS10275;pseudo=
#NZ_AP022171.1	GenBank	CDS	10173	10694	.	+	.	ID=H7R27_RS10275;Name=ugpC;codon_start=1;gene=ugpC;inference=COORDINATES: similar to AA sequence:RefSeq:NP_312323.2;is_partial=False;locus_tag=H7R27_RS10275;note=incomplete%3B partial in the middle of a contig%3B missing N-terminus%3B Derived by automated computational analysis using gene prediction method: Protein Homology.;product=sn-glycerol 3-phosphate ABC transporter ATP binding protein UgpC;pseudo=;transl_table=11
#NZ_AP022171.1	GenBank	gene	10691	11008	.	+	.	ID=H7R27_RS10280;Name=H7R27_RS10280;is_partial=False;locus_tag=H7R27_RS10280;old_locus_tag=WP5S18E09_20050;pseudo=
#NZ_AP022171.1	GenBank	CDS	10691	11008	.	+	.	ID=H7R27_RS10280;Name=H7R27_RS10280;go_function=GO:0008081 - phosphoric diester hydrolase activity [Evidence IEA];go_process=GO:0006629 - lipid metabolic process [Evidence IEA];codon_start=1;inference=COORDINATES: similar to AA sequence:RefSeq:NP_709219.1;is_partial=False;locus_tag=H7R27_RS10280;note=incomplete%3B partial in the middle of a contig%3B missing C-terminus%3B Derived by automated computational analysis using gene prediction method: Protein Homology.;old_locus_tag=WP5S18E09_20050;product=glycerophosphodiester phosphodiesterase family protein;pseudo=;transl_table=11
atb_hits_info_df = pd.read_csv("../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus2/NZ_AP022171.1_segment_0.hits_info.tsv", sep = "\t")
atb_hits_info_df.value_counts("organism")

organism
Escherichia coli                  187
Escherichia coli O25b:H4-ST131      4
Acinetobacter baumannii             1
Campylobacter jejuni                1
Escherichia coli KTE216             1
Escherichia coli O13/O135:H4        1
Shigella sonnei                     1
Name: count, dtype: int64

In [12]:
# long insertion: prophage
atb_hits_info_df = pd.read_csv("../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus2/NZ_CP098219.1_segment_0.hits_info.tsv", sep = "\t")
atb_hits_info_df.value_counts("organism")

organism
Escherichia coli                       83
Escherichia coli O145:H28               3
Salmonella enterica                     2
Salmonella enterica subsp. enterica     1
Name: count, dtype: int64

### Consensus 1

In [5]:
# get a list of all blocks that deviate from consensus paths (consider insertions and deletions!)

insertions, deletions, inversions = get_insertions_deletions_from_consensus(assignment_df, consensus_paths, path_dict, consensus = 1)
insertions_df = write_insertions_fasta(example_junction, example_pangraph, insertions, consensus = 1, save_df=True)
# set rerun_alignment to True if deletions are calculated for the first time
deletions_df = summarize_deletions_consensus(deletions, example_junction, example_pangraph, path_dict, assignment_df, consensus_id=1, parent_dir = "../results/atb_lookup/deletions", rerun_alignment=False, save_df=True)

# TODO: now correct fasta files, need to rerun downstream code with correct fasta files
# TODO: moved directory for insertion sequences to ../results/atb_lookup/insertions/, might need to update downstream code

Insertions:
NZ_OX030701.1 INSERTED: [6932368721519041699|-|1314867519434933921_1]
NZ_CP021935.1 INSERTED: [517157241956952768|+|]
NZ_CP076693.1 INSERTED: [964531385716605116|+|]_[16982887268023976258|+|]
NZ_CP128947.1 INSERTED: [964531385716605116|+|]_[16982887268023976258|+|]
NZ_CP107114.1 INSERTED: [517157241956952768|+|]
NZ_CP107172.1 INSERTED: [517157241956952768|+|]
NZ_CP030337.1 INSERTED: [6932368721519041699|+|16056383497489254679_1]
NZ_CP124429.1 INSERTED: [517157241956952768|-|]
NZ_CP018970.1 INSERTED: [6932368721519041699|-|17115477248436968411_1]
NZ_CP019015.1 INSERTED: [16982887268023976258|-|]_[964531385716605116|-|]
NZ_CP124460.1 INSERTED: [964531385716605116|+|]_[16982887268023976258|+|]
NZ_AP022044.1 INSERTED: [6932368721519041699|+|12883103544713419939_1]
NZ_AP022044.1 INSERTED: [6932368721519041699|-|14506298656834147691_1]
NZ_CP103562.1 INSERTED: [7844090243072536214|+|]
NZ_CP051661.1 INSERTED: [6932368721519041699|+|12883103544713419939_1]
NZ_CP051661.1 INSERTED: [6932368721519041699|+|10145330714100251892_1]
NZ_CP124455.1 INSERTED: [6932368721519041699|-|15558722379768673797_1]
NZ_CP023826.1 INSERTED: [6932368721519041699|-|17115477248436968411_1]
NZ_CP019012.1 INSERTED: [6932368721519041699|-|10145330714100251892_1]
NZ_CP036245.1 INSERTED: [964531385716605116|+|]_[16982887268023976258|+|]
NZ_CP059130.1 INSERTED: [517157241956952768|+|]
NZ_CP059130.1 INSERTED: [964531385716605116|+|]_[16982887268023976258|+|]
NZ_CP027534.1 INSERTED: [964531385716605116|+|]_[16982887268023976258|+|]
NZ_CP018979.1 INSERTED: [517157241956952768|-|]
NZ_CP134384.1 INSERTED: [185719230501067033|+|]
NZ_CP019008.1 INSERTED: [185719230501067033|+|]
NZ_CP124410.1 INSERTED: [6932368721519041699|+|9834685609301298901_1]
NZ_CP107122.1 INSERTED: [6932368721519041699|-|15558722379768673797_1]
NZ_CP107122.1 INSERTED: [6932368721519041699|+|11426489427845291638_1]
NZ_CP051663.1 INSERTED: [6932368721519041699|+|7987278316461198430_1]
NZ_CP107162.1 INSERTED: [6932368721519041699|-|15558722379768673797_1]
NZ_CP124374.1 INSERTED: [16982887268023976258|-|]_[964531385716605116|-|]
NZ_CP124424.1 INSERTED: [964531385716605116|+|]
NZ_AP026794.1 INSERTED: [964531385716605116|+|]_[16982887268023976258|+|]
NZ_AP026794.1 INSERTED: [16556873922195442803|+|]
NZ_CP021454.1 INSERTED: [6932368721519041699|-|913783977968963568_1]
NZ_AP026788.1 INSERTED: [964531385716605116|+|]_[16982887268023976258|+|]
NZ_AP026788.1 INSERTED: [16556873922195442803|+|]
NZ_CP124467.1 INSERTED: [185719230501067033|+|]
NZ_AP022326.1 INSERTED: [6932368721519041699|+|5100696243500885373_1]
NZ_AP022326.1 INSERTED: [6932368721519041699|+|6097212296783908714_1]
NZ_CP021179.1 INSERTED: [517157241956952768|+|]
NZ_CP010876.1 INSERTED: [16982887268023976258|-|]_[964531385716605116|-|]
NZ_CP133923.1 INSERTED: [185719230501067033|+|]
NZ_CP051659.1 INSERTED: [6932368721519041699|+|10145330714100251892_1]
NZ_LR890693.1 INSERTED: [6932368721519041699|-|11588582069103229002_1]
NZ_LR890693.1 INSERTED: [16982887268023976258|-|]_[964531385716605116|-|]
NZ_CP128907.1 INSERTED: [6932368721519041699|+|1708810210093552769_1]
NZ_CP107151.1 INSERTED: [6932368721519041699|-|15558722379768673797_1]

Deletions:
NZ_CP018970.1 DELETED: {'path': [13879318911159590194|+|]_[11455254306155687211|+|], 'left_nid': 10438114790459563195}
NZ_AP022044.1 DELETED: {'path': [11426489427845291638|+|]_[913783977968963568|+|]_[9242629882957449119|+|], 'left_nid': 7213204207337610003}
NZ_CP019012.1 DELETED: {'path': [12055620567302113403|+|], 'left_nid': 16454747171927747571}
NZ_CP134384.1 DELETED: {'path': [12883103544713419939|+|]_[11588582069103229002|+|]_[7754538651979209778|+|], 'left_nid': 13188367845728880729}
NZ_CP019008.1 DELETED: {'path': [12883103544713419939|+|]_[11588582069103229002|+|]_[7754538651979209778|+|], 'left_nid': 4204748230349595538}
NZ_CP051663.1 DELETED: {'path': [5100696243500885373|+|]_[15395175763379073292|+|]_[14506298656834147691|+|]_[11426489427845291638|+|]_[913783977968963568|+|]_[9242629882957449119|+|]_[1314867519434933921|+|]_[3035246746052306249|+|]_[16543294998939926181|+|]_[1708810210093552769|+|]_[17115477248436968411|+|]_[13879318911159590194|+|]_[11455254306155687211|+|]_[6304055291150384278|+|]_[6097212296783908714|+|]_[10145330714100251892|+|], 'left_nid': 9313648829512996371}
NZ_AP026788.1 DELETED: {'path': [6097212296783908714|+|], 'left_nid': 6810896770169503633}
NZ_CP124467.1 DELETED: {'path': [12883103544713419939|+|]_[11588582069103229002|+|]_[7754538651979209778|+|], 'left_nid': 25588021217311805}
NZ_CP133923.1 DELETED: {'path': [12883103544713419939|+|]_[11588582069103229002|+|]_[7754538651979209778|+|], 'left_nid': 3859946128404461677}
NZ_CP128907.1 DELETED: {'path': [17115477248436968411|+|]_[13879318911159590194|+|]_[11455254306155687211|+|]_[6304055291150384278|+|]_[6097212296783908714|+|], 'left_nid': 2891256612148042779}

In [5]:
insertions_df

,junction_name,consensus,genome_name,path,insertion,fasta_path,length,start_pos,end_pos
0,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_OX030701.1,[6932368721519041699|-|1314867519434933921_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,38342,39102
1,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP021935.1,[517157241956952768|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1248,5281,6529
2,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP076693.1,[964531385716605116|+|]_[16982887268023976258|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1863,22045,23908
3,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP128947.1,[964531385716605116|+|]_[16982887268023976258|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1863,22045,23908
4,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP107114.1,[517157241956952768|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1248,7143,8391
5,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP107172.1,[517157241956952768|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1248,7144,8392
6,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP030337.1,[6932368721519041699|+|16056383497489254679_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,19392,20152
7,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP124429.1,[517157241956952768|-|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1248,4881,6129
8,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP018970.1,[6932368721519041699|-|17115477248436968411_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,51236,52003
9,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP019015.1,[964531385716605116|-|]_[16982887268023976258|-|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1863,22668,22668
10,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP124460.1,[964531385716605116|+|]_[16982887268023976258|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1863,22046,23909
11,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_AP022044.1,[6932368721519041699|+|12883103544713419939_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,17700,18467
12,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_AP022044.1,[6932368721519041699|-|14506298656834147691_1],segment_1,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,35766,36534
13,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP103562.1,[7844090243072536214|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1446,4842,6288
14,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP051661.1,[6932368721519041699|+|12883103544713419939_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,17705,18481
15,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP051661.1,[6932368721519041699|+|10145330714100251892_1],segment_1,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,59353,60129
16,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP124455.1,[6932368721519041699|-|15558722379768673797_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,19208,19976
17,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP023826.1,[6932368721519041699|-|17115477248436968411_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,51236,52003
18,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP019012.1,[6932368721519041699|-|10145330714100251892_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,58505,59273
19,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP036245.1,[964531385716605116|+|]_[16982887268023976258|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1863,22045,23908
20,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP059130.1,[517157241956952768|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1248,4959,6212
21,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP059130.1,[964531385716605116|+|]_[16982887268023976258|+|],segment_1,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1863,23298,25161
22,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP027534.1,[964531385716605116|+|]_[16982887268023976258|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1863,22044,23907
23,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP018979.1,[517157241956952768|-|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1248,12652,13900
24,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP134384.1,[185719230501067033|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,4204,17382,21585
25,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP019008.1,[185719230501067033|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,4204,17382,21586
26,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP124410.1,[6932368721519041699|+|9834685609301298901_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,4325,5093
27,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP107122.1,[6932368721519041699|-|15558722379768673797_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,19241,20018
28,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP107122.1,[6932368721519041699|+|11426489427845291638_1],segment_1,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,36237,37013
29,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP051663.1,[6932368721519041699|+|7987278316461198430_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,21143,21907
30,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP107162.1,[6932368721519041699|-|15558722379768673797_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,19250,20018
31,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP124374.1,[964531385716605116|-|]_[16982887268023976258|-|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1863,22669,22669
32,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP124424.1,[964531385716605116|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1239,22027,23351
33,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_AP026794.1,[964531385716605116|+|]_[16982887268023976258|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1863,22044,23907
34,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_AP026794.1,[16556873922195442803|+|],segment_1,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1661,28059,29720
35,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP021454.1,[6932368721519041699|-|913783977968963568_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,35593,36370
36,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_AP026788.1,[964531385716605116|+|]_[16982887268023976258|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1863,22044,23907
37,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_AP026788.1,[16556873922195442803|+|],segment_1,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1661,28059,29720
38,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP124467.1,[185719230501067033|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,4204,17382,21586
39,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_AP022326.1,[6932368721519041699|+|5100696243500885373_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,21935,22712
40,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_AP022326.1,[6932368721519041699|+|6097212296783908714_1],segment_1,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,59169,59937
41,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP021179.1,[517157241956952768|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1248,45536,46784
42,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP010876.1,[964531385716605116|-|]_[16982887268023976258|-|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1863,22670,22670
43,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP133923.1,[185719230501067033|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,4204,17383,21587
44,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP051659.1,[6932368721519041699|+|10145330714100251892_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,58585,59345
45,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_LR890693.1,[6932368721519041699|-|11588582069103229002_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,18725,19485
46,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_LR890693.1,[964531385716605116|-|]_[16982887268023976258|-|],segment_1,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1863,23447,23447
47,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP128907.1,[6932368721519041699|+|1708810210093552769_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,48688,49448
48,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP107151.1,[6932368721519041699|-|15558722379768673797_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,19258,20018

In [6]:
load_all_insertions_summaries("../results/atb_lookup/insertions", example_junction, save_df=True)

,junction_name,consensus,genome_name,path,insertion,fasta_path,length,strand,start_pos,end_pos
0,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_OX030701.1,[6932368721519041699|-|1314867519434933921_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,-,38342,39102
1,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP021935.1,[517157241956952768|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1248,+,5281,6529
2,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP076693.1,[964531385716605116|+|]_[16982887268023976258|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1863,+,22045,23908
3,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP128947.1,[964531385716605116|+|]_[16982887268023976258|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1863,+,22045,23908
4,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP107114.1,[517157241956952768|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1248,+,7143,8391
5,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP107172.1,[517157241956952768|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1248,+,7144,8392
6,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP030337.1,[6932368721519041699|+|16056383497489254679_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,+,19392,20152
7,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP124429.1,[517157241956952768|-|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1248,-,4881,6129
8,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP018970.1,[6932368721519041699|-|17115477248436968411_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,-,51236,52003
9,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP019015.1,[964531385716605116|-|]_[16982887268023976258|-|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1863,-,22044,23907
10,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP124460.1,[964531385716605116|+|]_[16982887268023976258|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1863,+,22046,23909
11,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_AP022044.1,[6932368721519041699|+|12883103544713419939_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,+,17700,18467
12,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_AP022044.1,[6932368721519041699|-|14506298656834147691_1],segment_1,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,-,35766,36534
13,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP103562.1,[7844090243072536214|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1446,+,4842,6288
14,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP051661.1,[6932368721519041699|+|12883103544713419939_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,+,17705,18481
15,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP051661.1,[6932368721519041699|+|10145330714100251892_1],segment_1,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,+,59353,60129
16,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP124455.1,[6932368721519041699|-|15558722379768673797_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,-,19208,19976
17,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP023826.1,[6932368721519041699|-|17115477248436968411_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,-,51236,52003
18,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP019012.1,[6932368721519041699|-|10145330714100251892_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,-,58505,59273
19,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP036245.1,[964531385716605116|+|]_[16982887268023976258|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1863,+,22045,23908
20,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP059130.1,[517157241956952768|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1248,+,4959,6212
21,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP059130.1,[964531385716605116|+|]_[16982887268023976258|+|],segment_1,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1863,+,23298,25161
22,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP027534.1,[964531385716605116|+|]_[16982887268023976258|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1863,+,22044,23907
23,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP018979.1,[517157241956952768|-|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1248,-,12652,13900
24,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP134384.1,[185719230501067033|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,4204,+,17382,21585
25,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP019008.1,[185719230501067033|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,4204,+,17382,21586
26,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP124410.1,[6932368721519041699|+|9834685609301298901_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,+,4325,5093
27,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP107122.1,[6932368721519041699|-|15558722379768673797_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,-,19241,20018
28,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP107122.1,[6932368721519041699|+|11426489427845291638_1],segment_1,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,+,36237,37013
29,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP051663.1,[6932368721519041699|+|7987278316461198430_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,+,21143,21907
30,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP107162.1,[6932368721519041699|-|15558722379768673797_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,-,19250,20018
31,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP124374.1,[964531385716605116|-|]_[16982887268023976258|-|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1863,-,22045,23908
32,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP124424.1,[964531385716605116|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1239,+,22027,23351
33,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_AP026794.1,[964531385716605116|+|]_[16982887268023976258|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1863,+,22044,23907
34,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_AP026794.1,[16556873922195442803|+|],segment_1,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1661,+,28059,29720
35,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP021454.1,[6932368721519041699|-|913783977968963568_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,-,35593,36370
36,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_AP026788.1,[964531385716605116|+|]_[16982887268023976258|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1863,+,22044,23907
37,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_AP026788.1,[16556873922195442803|+|],segment_1,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1661,+,28059,29720
38,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP124467.1,[185719230501067033|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,4204,+,17382,21586
39,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_AP022326.1,[6932368721519041699|+|5100696243500885373_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,+,21935,22712
40,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_AP022326.1,[6932368721519041699|+|6097212296783908714_1],segment_1,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,+,59169,59937
41,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP021179.1,[517157241956952768|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1248,+,45536,46784
42,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP010876.1,[964531385716605116|-|]_[16982887268023976258|-|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1863,-,22027,23920
43,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP133923.1,[185719230501067033|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,4204,+,17383,21587
44,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP051659.1,[6932368721519041699|+|10145330714100251892_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,+,58585,59345
45,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_LR890693.1,[6932368721519041699|-|11588582069103229002_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,-,18725,19485
46,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_LR890693.1,[964531385716605116|-|]_[16982887268023976258|-|],segment_1,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,1863,-,22804,24697
47,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP128907.1,[6932368721519041699|+|1708810210093552769_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,+,48688,49448
48,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP107151.1,[6932368721519041699|-|15558722379768673797_1],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,768,-,19258,20018
49,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_2,NZ_AP022171.1,[18228278273347143766|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,820,+,10166,10986
50,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_2,NZ_CP098219.1,[2278011600046483881|+|],segment_0,../results/atb_lookup/insertions/CIRMBUYJFK_f_...,37622,+,3488,41110

In [ ]:
# get start and end of insertion (only first block of insertion, use for start and use last block of insertion for end)
example_pangraph.nodes[insertions['NZ_OX030701.1'][0].nodes[0].nid].end

# TODO: make plot that marks insertions and deletions on the pangraph visualization
# maybe dark red for insertions and oragne lines for deletions
# add hover for deletions that gives the location and size of the deletion, for insertions as well
# could be that there are several deletions at same location because I'm splitting them when I'm splitting inversions

39102

In [25]:
deletions['NZ_CP018970.1']

[[13879318911159590194|+|]_[11455254306155687211|+|]]

In [6]:
deletions_df

,junction_name,consensus,genome_name,path,deletion,consensus_sequence,length
0,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP018970.1,[13879318911159590194|+|]_[1145525430615568721...,deletion0,atgaaatcaatgtaactgtaatgaattttaatgatggtgccttttg...,6336
1,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_AP022044.1,[11426489427845291638|+|]_[913783977968963568|...,deletion0,agggcgactattatggcccaatcggacgatgaatatgctgcagcgg...,1415
2,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP019012.1,[12055620567302113403|+|],deletion0,caacatcccatttcgattattcctgtttcatttttgcttgccagtg...,2807
3,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP134384.1,[12883103544713419939|+|]_[1158858206910322900...,deletion0,acagactttccctacttcgttgagagtacacctagtacaatcaagg...,1629
4,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP019008.1,[12883103544713419939|+|]_[1158858206910322900...,deletion0,acagactttccctacttcgttgagagtacacctagtacaatcaagg...,1629
5,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP051663.1,[5100696243500885373|+|]_[15395175763379073292...,deletion0,atgatgatttaacgagccataacaaaaccctgcctcggaggttttt...,37434
6,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_AP026788.1,[6097212296783908714|+|],deletion0,agtaattaaactgatgtgtccctttactggcctggcgatagatacc...,302
7,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP124467.1,[12883103544713419939|+|]_[1158858206910322900...,deletion0,acagactttccctacttcgttgagagtacacctagtacaatcaagg...,1629
8,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP133923.1,[12883103544713419939|+|]_[1158858206910322900...,deletion0,acagactttccctacttcgttgagagtacacctagtacaatcaagg...,1629
9,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP128907.1,[17115477248436968411|+|]_[1387931891115959019...,deletion0,taagatttgccgtcactgatttgaaacggcggcagaaaacctgccg...,9704

run lexicmap search on cluster for all sequences: bash run_all_lexicmap.sh ./queries/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1

In [ ]:
# retrieve SAM... to look up in NCBI:
retrieve_SAMids_txt(parent_dir="../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1")

retrieve info from NCBI: bash fetch_biosamples_consensus1.sh out of this folder results/atb_lookup

In [ ]:
# merge results
combine_NCBI_atb_results(parent_dir="../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1")

In [141]:
pd.read_csv("../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP030337.1_segment_0.ncbi_results.tsv", sep="\t").value_counts('organism')

organism
Campylobacter jejuni         9
Escherichia coli             2
Helicobacter winghamensis    1
Klebsiella pneumoniae        1
Name: count, dtype: int64

In [ ]:
# TODO: should I run blocks seperately or insertions as a whole
# TODO: rerun lexicmap ... now with correctly inverted sequences

Information about different insertion sequences:

- 5 different versions of this block, if a block is twice in one sequence it is always the same version twice, versions can be inserted or not inserted, found between 1 and 9 times in other genomes
    - NZ_CP107151.1, blocks [6932368721519041699|-|]: majority of hits are Mycoplasma mycoides or E. coli and some others, IS1 based on annotation, same insertion in NZ_CP107162.1 and NZ_CP107122.1 blocks [6932368721519041699|-|], same hits, NZ_CP107122.1 even has same insertion a second time[6932368721519041699|+|], NZ_CP128907.1|segment_0 path[6932368721519041699|+|1708810210093552769] length760, NZ_AP022326.1|segment_0 path[6932368721519041699|+|5100696243500885373] length777, NZ_AP022326.1|segment_1 path[6932368721519041699|+|6097212296783908714] length777, NZ_CP124410.1: path[6932368721519041699|+|] IS1, Mycoplasma mycoides and E.coli and Campylobacter jejuni and some more
    - NZ_CP021454.1|segment_0 path[6932368721519041699|-|913783977968963568] length777 and NZ_CP019012.1|segment_0 path[6932368721519041699|-|10145330714100251892] length768 (only found once in genome), inverted, IS1, only 4 hits and different ones --> difference within block!
    - NZ_OX030701.1|segment_0 path[6932368721519041699|-|] length760, NZ_CP018970.1|segment_0 path[6932368721519041699|-|17115477248436968411] length767, NZ_CP023826.1|segment_0 path[6932368721519041699|-|17115477248436968411] length767, NZ_LR890693.1|segment_0 path[6932368721519041699|-|11588582069103229002] length760, NZ_CP051661.1|segment_1 path[6932368721519041699|+|10145330714100251892] length776 and segment_0 path[6932368721519041699|+|12883103544713419939] length776, NZ_CP051663.1|segment_0 path[6932368721519041699|+|7987278316461198430] length764, NZ_CP051659.1|segment_0 path[6932368721519041699|+|10145330714100251892] length760, NZ_CP018970.1|segment_0 path[6932368721519041699|-|17115477248436968411] length767, NZ_CP023826.1|segment_0 path[6932368721519041699|-|17115477248436968411] length767, NZ_CP124455.1|segment_0 path[6932368721519041699|-|15558722379768673797] length768, same hits, less hits, IS1
    - NZ_CP030337.1|segment_0 path[6932368721519041699|+|16056383497489254679] length760, Campylobacter jejuni version (?)
    - NZ_AP022044.1|segment_0 path[6932368721519041699|+|12883103544713419939] length767 and NZ_AP022044.1|segment_1 path[6932368721519041699|-|14506298656834147691] length767, new version, mostly E.coli, 25 hits

- NZ_CP103562.1: path[7844090243072536214|+|] E. coli and some single different ones, IS3, found twice in genome

- double block: all found twice (once elsewhere in genome), all at same position, just some inverted
    - NZ_CP124374.1 and NZ_CP019015.1: [16982887268023976258|-|]_[964531385716605116|-|] ISL3 (both blogs together): no hits (TODO: change parameters and rerun or run blogs seperately)
    - NZ_CP059130.1 (segment 1), NZ_AP026788.1 and NZ_AP026794.1, [964531385716605116|+|]_[16982887268023976258|+|], NZ_CP124460.1|segment_0 path[964531385716605116|+|]_[16982887268023976258|+|] length1863, NZ_CP027534.1|segment_0 path[964531385716605116|+|]_[16982887268023976258|+|] length1863, NZ_CP128947.1|segment_0 path[964531385716605116|+|]_[16982887268023976258|+|] length1863: ISL3, mostly E.coli, same hits
    - NZ_LR890693.1|segment_1 path[964531385716605116|-|]_[16982887268023976258|-|], NZ_CP010876.1|segment_0 path[964531385716605116|-|]_[16982887268023976258|-|] length1893, (order was inverted here) length1893, this one got hits now, all E.coli (why hits even though sequences don't fit)
- NZ_CP124424.1|segment_0 path[964531385716605116|+|] length1324, exist as partly insertion (only first block), less hits, E.coli and Lelliottia amnigena, ISL3, found twice


- NZ_CP021935.1, NZ_CP059130.1 (segment 0), NZ_CP107114.1 and NZ_CP107172.1 (identical), NZ_CP107114.1, NZ_CP107172, NZ_CP021179.1, NZ_CP018979.1 and NZ_CP124429.1 (inverted): 517157241956952768 IS3, 100% hits in E.coli and in other bacteria, mostly E. coli, all get the same hits, they might differ in a few bases or some bases at ends, inserted at different positions in genome, one has 3 base overhang, apart from that they are completely the same, different amount of hits in genome (between 2 and 7)

- NZ_AP026788.1 and NZ_AP026794.1: path[16556873922195442803|+|] IS1380, E. coli, Klebsiella pneumoniae, Pseudomonas aeruginosa,Salmonella enterica all frequent, many more, twice in genome and both have same hits

- NZ_CP019008.1|segment_0 path[185719230501067033|+|] length4204, NZ_CP133923.1|segment_0 path[185719230501067033|+|] length4204, NZ_CP124467.1|segment_0 path[185719230501067033|+|] length4204, NZ_CP134384.1|segment_0 path[185719230501067033|+|] length4203 (one nucleotide shorter): 200 hits that are all E. coli. all sequences identical, only once in genome


Difference between consensus 1 and consensus 2 in one big prophage according to annotations

Be careful to not confuse context for next block!

In [87]:
pd.read_csv("../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_AP022044.1_segment_0.hits_info.tsv", sep="\t")[["query", "qlen", 'hits', 'sgenome', 'qcovGnm', 'cls', 'hsp',
       'qcovHSP', 'alenHSP', 'pident', 'gaps', 'evalue', 'bitscore', 'organism', 'strain',
       'serovar', 'sequence_type']]

,query,qlen,hits,sgenome,qcovGnm,cls,hsp,qcovHSP,alenHSP,pident,gaps,evalue,bitscore,organism,strain,serovar,sequence_type
0,NZ_AP022044.1|segment_0,767,25,SAMEA4062129,100.0,1,1,100.0,768,99.870,1,0.0,1389,Escherichia coli,NaN,NaN,NaN
1,NZ_AP022044.1|segment_0,767,25,SAMN14049574,100.0,1,1,100.0,768,99.870,1,0.0,1389,Escherichia coli,E. coli QEC12-15,NaN,NaN
2,NZ_AP022044.1|segment_0,767,25,SAMN07508953,100.0,1,1,100.0,768,99.870,1,0.0,1389,Escherichia coli,29-KPC,NaN,NaN
3,NZ_AP022044.1|segment_0,767,25,SAMEA104040230,100.0,1,1,100.0,768,99.870,1,0.0,1389,Escherichia coli,NaN,NaN,NaN
4,NZ_AP022044.1|segment_0,767,25,SAMEA111271919,100.0,1,1,100.0,768,99.870,1,0.0,1389,Escherichia coli,NaN,NaN,NaN
5,NZ_AP022044.1|segment_0,767,25,SAMN08382692,100.0,1,1,100.0,768,99.870,1,0.0,1389,Escherichia coli,GASRECE110,NaN,NaN
6,NZ_AP022044.1|segment_0,767,25,SAMEA111273518,100.0,1,1,100.0,768,99.870,1,0.0,1389,Escherichia coli,NaN,NaN,NaN
7,NZ_AP022044.1|segment_0,767,25,SAMN18977267,100.0,1,1,100.0,768,99.870,1,0.0,1389,Escherichia coli,missing,missing,NaN
8,NZ_AP022044.1|segment_0,767,25,SAMEA111273646,100.0,1,1,100.0,768,99.870,1,0.0,1389,Escherichia coli,NaN,NaN,NaN
9,NZ_AP022044.1|segment_0,767,25,SAMEA111273548,100.0,1,1,100.0,768,99.870,1,0.0,1389,Escherichia coli,NaN,NaN,NaN
10,NZ_AP022044.1|segment_0,767,25,SAMEA111273647,100.0,1,1,100.0,768,99.870,1,0.0,1389,Escherichia coli,NaN,NaN,NaN
11,NZ_AP022044.1|segment_0,767,25,SAMEA111273667,100.0,1,1,100.0,768,99.870,1,0.0,1389,Escherichia coli,NaN,NaN,NaN
12,NZ_AP022044.1|segment_0,767,25,SAMN01922332,100.0,1,1,100.0,768,99.870,1,0.0,1389,Escherichia coli ADL-327,ADL-327,NaN,NaN
13,NZ_AP022044.1|segment_0,767,25,SAMN15904810,100.0,1,1,100.0,768,99.870,1,0.0,1389,Escherichia coli,hkcpe141,NaN,NaN
14,NZ_AP022044.1|segment_0,767,25,SAMN26379194,100.0,1,1,100.0,768,99.870,1,0.0,1389,Escherichia coli,PFEEC0739,NaN,NaN
15,NZ_AP022044.1|segment_0,767,25,SAMEA111274498,100.0,1,1,100.0,768,99.870,1,0.0,1389,Escherichia coli,NaN,NaN,NaN
16,NZ_AP022044.1|segment_0,767,25,SAMEA111274494,100.0,1,1,100.0,768,99.870,1,0.0,1389,Escherichia coli,NaN,NaN,NaN
17,NZ_AP022044.1|segment_0,767,25,SAMD00500056,100.0,1,1,100.0,768,99.870,1,0.0,1389,Escherichia coli,JBCDAFJ-19-0051,NaN,NaN
18,NZ_AP022044.1|segment_0,767,25,SAMD00497908,100.0,1,1,100.0,768,99.870,1,0.0,1389,Escherichia coli,JBAJAAH-19-0014,NaN,NaN
19,NZ_AP022044.1|segment_0,767,25,SAMN15904789,100.0,1,1,100.0,768,99.870,1,0.0,1389,Klebsiella quasipneumoniae,hkcpe120,NaN,NaN
20,NZ_AP022044.1|segment_0,767,25,SAMEA6155701,100.0,1,1,100.0,768,99.870,1,0.0,1389,Escherichia coli,NaN,NaN,NaN
21,NZ_AP022044.1|segment_0,767,25,SAMEA7230815,100.0,1,1,100.0,768,99.740,1,0.0,1386,Escherichia coli,NaN,NaN,NaN
22,NZ_AP022044.1|segment_0,767,25,SAMN30575479,100.0,1,1,100.0,768,98.698,1,0.0,1350,Enterobacter cloacae,missing,NaN,NaN
23,NZ_AP022044.1|segment_0,767,25,SAMN26796500,100.0,1,1,100.0,768,98.307,1,0.0,1335,Enterobacter cloacae,Enterobacter_cloacae_P36220121,NaN,NaN
24,NZ_AP022044.1|segment_0,767,25,SAMN41034631,100.0,1,1,100.0,768,98.177,1,0.0,1332,Escherichia coli,VUTI177,NaN,NaN

In [ ]:
# TODO: do I also search deletions in the database?

'GGTAATGACTCCAACTTACTGATAGTGTTTTATGTTCAGATAATGCCCGATGACTTTGTCATGCAGCTCCACCGATTTTGAGAACGACAGTGACTTCCGTCCCAGCCTTGCCAGATGTTGTCTCAGATTCAGGTTATGTCGCTCAATGCGCTGAGTGTAACGCTTGCTGATTACGTGCAGCTTTCCCTTCAGGCGGGATTCATACAGCGGCCAGCCATCCGTCATCCATACCACGACCTCAAAGGCCGACAGCAGGCTCAGAAGACGCTCCAGTGTGGCCAGAGTGCGTTCACCGAAGACGTGCGCCACAACCGTCCTCCGTATCCTGTCATACGCGTAAAACAGCCAGCGCTGACGTGATTTAGCACCGACGTAGCCCCACTGTTCGTCCATTTCAGCGCAGACAATCACATCACTGCCCGGCTGTATGCGCGAGGTTACCGACTGCGGCCTGAGTTTTTTAAGTGACGTAAAATCGTGTTGAGGCCAACGCCCATAATGCGGGCGGTTGCCCGGCATCCAACACCATTCATGGCCATATCAATGATTTTCTGGTGTGTACCGGGTTGAGAAGCGGTGTAAGTGAACTGCAGTTGCCATGTTTTACGGCAGTGAGAGCAGAGATAGCGCTGATGTCCGGCAGTACTTTTACCGTTACGCACCACGCCTTCAGTAGCTGAGCAGGAGGGACAACTGATGGAGATGGAAGCCACGGGAGCACCTCAAAAACACCATCATACACTAAATCAGTAAGTTGGCA'

## Search insertion sequences in their own genome

In [19]:
# make sure that all genome fasta files exist
#convert_gbk_fasta(gbk_folder = "../data/gbk", fasta_folder = "../results/genome_fastas")

In [4]:
insertions_df = find_insertion_hits_own_genome(genome_root = "../results/genome_fastas", insertions_seq_dir=f"../results/atb_lookup/{example_junction}")

[M::mm_idx_gen::0.123*0.82] collected minimizers
[M::mm_idx_gen::0.136*0.94] sorted minimizers
[M::main::0.136*0.94] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.141*0.94] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.145*0.94] distinct minimizers: 504461 (98.70% are singletons); average occurrences: 1.024; average spacing: 9.992; total length: 5163545
[M::worker_pipeline::0.146*0.94] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/genome_fastas/NZ_CP124455.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP124455.1_segment_0.fasta
[M::main] Real time: 0.153 sec; CPU: 0.144 sec; Peak RSS: 0.046 GB
[M::mm_idx_gen::0.064*1.06] collected minimizers
[M::mm_idx_gen::0.072*1.26] sorted minimizers
[M::main::0.072*1.26] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.076*1.25] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.080*1.23] distinct minimizers: 496890 (99.14% are singletons); average occurrences: 1.021; average spacing: 9.992; total length: 5071232
[M::worker_pipeline::0.081*1.23] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/genome_fastas/NZ_CP107122.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP107122.1_segment_0.fasta
[M::main] Real time: 0.088 sec; CPU: 0.107 sec; Peak RSS: 0.043 GB
[M::mm_idx_gen::0.061*1.04] collected minimizers
[M::mm_idx_gen::0.069*1.25] sorted minimizers
[M::main::0.069*1.25] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.074*1.23] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.078*1.22] distinct minimizers: 488846 (99.19% are singletons); average occurrences: 1.016; average spacing: 9.993; total length: 4965000
[M::worker_pipeline::0.079*1.22] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/genome_fastas/NZ_CP128947.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP128947.1_segment_0.fasta
[M::main] Real time: 0.087 sec; CPU: 0.104 sec; Peak RSS: 0.040 GB
[M::mm_idx_gen::0.065*1.03] collected minimizers
[M::mm_idx_gen::0.074*1.24] sorted minimizers
[M::main::0.074*1.24] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.079*1.23] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.083*1.22] distinct minimizers: 512762 (99.05% are singletons); average occurrences: 1.018; average spacing: 9.995; total length: 5216726
[M::worker_pipeline::0.084*1.22] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/genome_fastas/NZ_CP059130.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP059130.1_segment_1.fasta
[M::main] Real time: 0.091 sec; CPU: 0.109 sec; Peak RSS: 0.046 GB
[M::mm_idx_gen::0.064*1.05] collected minimizers
[M::mm_idx_gen::0.073*1.26] sorted minimizers
[M::main::0.073*1.26] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.078*1.25] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.082*1.24] distinct minimizers: 489014 (99.15% are singletons); average occurrences: 1.019; average spacing: 9.993; total length: 4978191
[M::worker_pipeline::0.082*1.23] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/genome_fastas/NZ_CP124460.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP124460.1_segment_0.fasta
[M::main] Real time: 0.090 sec; CPU: 0.109 sec; Peak RSS: 0.044 GB
[M::mm_idx_gen::0.066*1.05] collected minimizers
[M::mm_idx_gen::0.075*1.25] sorted minimizers
[M::main::0.075*1.25] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.079*1.24] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.084*1.22] distinct minimizers: 495762 (98.85% are singletons); average occurrences: 1.022; average spacing: 9.992; total length: 5061196
[M::worker_pipeline::0.085*1.22] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/genome_fastas/NZ_LR890693.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_LR890693.1_segment_0.fasta
[M::main] Real time: 0.091 sec; CPU: 0.110 sec; Peak RSS: 0.044 GB
[M::mm_idx_gen::0.063*1.06] collected minimizers
[M::mm_idx_gen::0.070*1.26] sorted minimizers
[M::main::0.070*1.26] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.075*1.24] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.079*1.23] distinct minimizers: 492759 (99.28% are singletons); average occurrences: 1.018; average spacing: 9.994; total length: 5010884
[M::worker_pipeline::0.080*1.23] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/genome_fastas/NZ_CP010876.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP010876.1_segment_0.fasta
[M::main] Real time: 0.087 sec; CPU: 0.105 sec; Peak RSS: 0.042 GB
[M::mm_idx_gen::0.065*1.03] collected minimizers
[M::mm_idx_gen::0.073*1.24] sorted minimizers
[M::main::0.073*1.24] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.078*1.23] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.082*1.22] distinct minimizers: 504923 (99.18% are singletons); average occurrences: 1.017; average spacing: 9.993; total length: 5129468
[M::worker_pipeline::0.083*1.21] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/genome_fastas/NZ_CP023826.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP023826.1_segment_0.fasta
[M::main] Real time: 0.091 sec; CPU: 0.108 sec; Peak RSS: 0.047 GB
[M::mm_idx_gen::0.063*1.05] collected minimizers
[M::mm_idx_gen::0.071*1.26] sorted minimizers
[M::main::0.072*1.26] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.076*1.24] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.080*1.23] distinct minimizers: 489613 (99.23% are singletons); average occurrences: 1.018; average spacing: 9.993; total length: 4978342
[M::worker_pipeline::0.081*1.23] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/genome_fastas/NZ_CP021454.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP021454.1_segment_0.fasta
[M::main] Real time: 0.089 sec; CPU: 0.107 sec; Peak RSS: 0.043 GB
[M::mm_idx_gen::0.062*1.06] collected minimizers
[M::mm_idx_gen::0.070*1.27] sorted minimizers
[M::main::0.070*1.27] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.075*1.25] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.079*1.24] distinct minimizers: 472327 (97.85% are singletons); average occurrences: 1.037; average spacing: 9.995; total length: 4893409
[M::worker_pipeline::0.080*1.24] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/genome_fastas/NZ_CP124467.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP124467.1_segment_0.fasta
[M::main] Real time: 0.086 sec; CPU: 0.105 sec; Peak RSS: 0.041 GB
[M::mm_idx_gen::0.063*1.03] collected minimizers
[M::mm_idx_gen::0.071*1.14] sorted minimizers
[M::main::0.071*1.25] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.076*1.24] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.080*1.22] distinct minimizers: 488238 (99.19% are singletons); average occurrences: 1.019; average spacing: 9.994; total length: 4974345
[M::worker_pipeline::0.080*1.22] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/genome_fastas/NZ_CP124429.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP124429.1_segment_0.fasta
[M::main] Real time: 0.088 sec; CPU: 0.105 sec; Peak RSS: 0.043 GB
[M::mm_idx_gen::0.064*1.05] collected minimizers
[M::mm_idx_gen::0.073*1.26] sorted minimizers
[M::main::0.073*1.26] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.078*1.24] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.082*1.23] distinct minimizers: 495762 (98.85% are singletons); average occurrences: 1.022; average spacing: 9.992; total length: 5061196
[M::worker_pipeline::0.082*1.23] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/genome_fastas/NZ_LR890693.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_LR890693.1_segment_1.fasta
[M::main] Real time: 0.089 sec; CPU: 0.108 sec; Peak RSS: 0.045 GB
[M::mm_idx_gen::0.065*1.03] collected minimizers
[M::mm_idx_gen::0.074*1.26] sorted minimizers
[M::main::0.074*1.26] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.079*1.24] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.083*1.23] distinct minimizers: 506371 (99.21% are singletons); average occurrences: 1.016; average spacing: 9.993; total length: 5141314
[M::worker_pipeline::0.084*1.23] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/genome_fastas/NZ_CP021935.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP021935.1_segment_0.fasta
[M::main] Real time: 0.090 sec; CPU: 0.109 sec; Peak RSS: 0.045 GB
[M::mm_idx_gen::0.069*1.04] collected minimizers
[M::mm_idx_gen::0.077*1.24] sorted minimizers
[M::main::0.077*1.24] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.082*1.23] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.087*1.21] distinct minimizers: 509570 (97.84% are singletons); average occurrences: 1.033; average spacing: 9.996; total length: 5259570
[M::worker_pipeline::0.087*1.21] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/genome_fastas/NZ_CP107114.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP107114.1_segment_0.fasta
[M::main] Real time: 0.094 sec; CPU: 0.112 sec; Peak RSS: 0.055 GB
[M::mm_idx_gen::0.066*1.04] collected minimizers
[M::mm_idx_gen::0.074*1.24] sorted minimizers
[M::main::0.074*1.24] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.079*1.22] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.083*1.21] distinct minimizers: 500234 (98.88% are singletons); average occurrences: 1.019; average spacing: 9.995; total length: 5096686
[M::worker_pipeline::0.084*1.21] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/genome_fastas/NZ_CP107172.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP107172.1_segment_0.fasta
[M::main] Real time: 0.090 sec; CPU: 0.107 sec; Peak RSS: 0.045 GB
[M::mm_idx_gen::0.065*1.04] collected minimizers
[M::mm_idx_gen::0.072*1.24] sorted minimizers
[M::main::0.072*1.24] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.077*1.23] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.081*1.21] distinct minimizers: 495194 (98.93% are singletons); average occurrences: 1.020; average spacing: 9.992; total length: 5048620
[M::worker_pipeline::0.082*1.21] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/genome_fastas/NZ_CP051659.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP051659.1_segment_0.fasta
[M::main] Real time: 0.092 sec; CPU: 0.107 sec; Peak RSS: 0.044 GB
[M::mm_idx_gen::0.065*1.03] collected minimizers
[M::mm_idx_gen::0.073*1.24] sorted minimizers
[M::main::0.073*1.24] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.079*1.22] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.083*1.21] distinct minimizers: 510090 (98.23% are singletons); average occurrences: 1.026; average spacing: 9.994; total length: 5228864
[M::worker_pipeline::0.083*1.21] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/genome_fastas/NZ_CP018979.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP018979.1_segment_0.fasta
[M::main] Real time: 0.090 sec; CPU: 0.107 sec; Peak RSS: 0.045 GB
[M::mm_idx_gen::0.061*1.07] collected minimizers
[M::mm_idx_gen::0.068*1.28] sorted minimizers
[M::main::0.068*1.28] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.073*1.26] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.077*1.24] distinct minimizers: 496890 (99.14% are singletons); average occurrences: 1.021; average spacing: 9.992; total length: 5071232
[M::worker_pipeline::0.078*1.24] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/genome_fastas/NZ_CP107122.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP107122.1_segment_1.fasta
[M::main] Real time: 0.084 sec; CPU: 0.103 sec; Peak RSS: 0.045 GB
[M::mm_idx_gen::0.062*1.07] collected minimizers
[M::mm_idx_gen::0.070*1.28] sorted minimizers
[M::main::0.070*1.28] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.074*1.26] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.079*1.25] distinct minimizers: 512762 (99.05% are singletons); average occurrences: 1.018; average spacing: 9.995; total length: 5216726
[M::worker_pipeline::0.080*1.24] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/genome_fastas/NZ_CP059130.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP059130.1_segment_0.fasta
[M::main] Real time: 0.086 sec; CPU: 0.105 sec; Peak RSS: 0.049 GB
[M::mm_idx_gen::0.062*1.03] collected minimizers
[M::mm_idx_gen::0.071*1.25] sorted minimizers
[M::main::0.071*1.25] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.075*1.24] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.079*1.22] distinct minimizers: 493022 (99.23% are singletons); average occurrences: 1.017; average spacing: 9.993; total length: 5012084
[M::worker_pipeline::0.080*1.22] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/genome_fastas/NZ_CP021179.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP021179.1_segment_0.fasta
[M::main] Real time: 0.086 sec; CPU: 0.104 sec; Peak RSS: 0.044 GB
[M::mm_idx_gen::0.067*1.02] collected minimizers
[M::mm_idx_gen::0.076*1.23] sorted minimizers
[M::main::0.076*1.23] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.080*1.21] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.084*1.20] distinct minimizers: 514601 (98.63% are singletons); average occurrences: 1.023; average spacing: 9.992; total length: 5259387
[M::worker_pipeline::0.085*1.20] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/genome_fastas/NZ_CP018970.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP018970.1_segment_0.fasta
[M::main] Real time: 0.091 sec; CPU: 0.108 sec; Peak RSS: 0.052 GB
[M::mm_idx_gen::0.075*0.98] collected minimizers
[M::mm_idx_gen::0.084*1.15] sorted minimizers
[M::main::0.084*1.15] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.091*1.14] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.095*1.13] distinct minimizers: 496945 (98.97% are singletons); average occurrences: 1.021; average spacing: 9.993; total length: 5070006
[M::worker_pipeline::0.095*1.13] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/genome_fastas/NZ_OX030701.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_OX030701.1_segment_0.fasta
[M::main] Real time: 0.102 sec; CPU: 0.114 sec; Peak RSS: 0.044 GB
[M::mm_idx_gen::0.067*1.03] collected minimizers
[M::mm_idx_gen::0.075*1.23] sorted minimizers
[M::main::0.075*1.23] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.081*1.21] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.085*1.20] distinct minimizers: 507513 (98.75% are singletons); average occurrences: 1.021; average spacing: 9.994; total length: 5181038
[M::worker_pipeline::0.085*1.20] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/genome_fastas/NZ_CP076693.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP076693.1_segment_0.fasta
[M::main] Real time: 0.091 sec; CPU: 0.108 sec; Peak RSS: 0.048 GB
[M::mm_idx_gen::0.065*1.04] collected minimizers
[M::mm_idx_gen::0.074*1.24] sorted minimizers
[M::main::0.074*1.24] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.079*1.22] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.083*1.21] distinct minimizers: 502386 (99.09% are singletons); average occurrences: 1.022; average spacing: 9.992; total length: 5128182
[M::worker_pipeline::0.084*1.20] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/genome_fastas/NZ_CP107162.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP107162.1_segment_0.fasta
[M::main] Real time: 0.090 sec; CPU: 0.108 sec; Peak RSS: 0.045 GB
[M::mm_idx_gen::0.063*1.04] collected minimizers
[M::mm_idx_gen::0.071*1.25] sorted minimizers
[M::main::0.071*1.25] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.076*1.23] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.080*1.22] distinct minimizers: 491236 (98.56% are singletons); average occurrences: 1.026; average spacing: 9.994; total length: 5038168
[M::worker_pipeline::0.081*1.22] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/genome_fastas/NZ_AP022326.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_AP022326.1_segment_0.fasta
[M::main] Real time: 0.087 sec; CPU: 0.105 sec; Peak RSS: 0.043 GB
[M::mm_idx_gen::0.065*1.03] collected minimizers
[M::mm_idx_gen::0.073*1.23] sorted minimizers
[M::main::0.073*1.23] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.078*1.22] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.083*1.21] distinct minimizers: 508685 (98.70% are singletons); average occurrences: 1.020; average spacing: 9.995; total length: 5187769
[M::worker_pipeline::0.083*1.21] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/genome_fastas/NZ_CP036245.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP036245.1_segment_0.fasta

In [5]:
insertions_df.sort_values(['consensus','insertion_path'])

,junction_name,consensus,genome_name,insertion_path,insertion_length,segment,hits_in_genome
27,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_AP026794.1,[16556873922195442803|+|],1661,segment_1,2
28,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_AP026788.1,[16556873922195442803|+|],1661,segment_1,2
9,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP124467.1,[185719230501067033|+|],4204,segment_0,1
29,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP134384.1,[185719230501067033|+|],4204,segment_0,1
36,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP133923.1,[185719230501067033|+|],4204,segment_0,1
41,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP019008.1,[185719230501067033|+|],4204,segment_0,1
12,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP021935.1,[517157241956952768|+|],1248,segment_0,3
13,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP107114.1,[517157241956952768|+|],1248,segment_0,5
14,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP107172.1,[517157241956952768|+|],1248,segment_0,2
18,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP059130.1,[517157241956952768|+|],1248,segment_0,4
19,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP021179.1,[517157241956952768|+|],1248,segment_0,7
10,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP124429.1,[517157241956952768|-|],1248,segment_0,6
16,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP018979.1,[517157241956952768|-|],1248,segment_0,2
15,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP051659.1,[6932368721519041699|+|10145330714100251892_1],768,segment_0,3
39,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP051661.1,[6932368721519041699|+|10145330714100251892_1],768,segment_1,4
17,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP107122.1,[6932368721519041699|+|11426489427845291638_1],768,segment_1,9
30,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP051661.1,[6932368721519041699|+|12883103544713419939_1],768,segment_0,4
34,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_AP022044.1,[6932368721519041699|+|12883103544713419939_1],768,segment_0,9
32,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP030337.1,[6932368721519041699|+|16056383497489254679_1],768,segment_0,3
26,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP128907.1,[6932368721519041699|+|1708810210093552769_1],768,segment_0,3
24,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_AP022326.1,[6932368721519041699|+|5100696243500885373_1],768,segment_0,4
42,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_AP022326.1,[6932368721519041699|+|6097212296783908714_1],768,segment_1,5
45,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP051663.1,[6932368721519041699|+|7987278316461198430_1],768,segment_0,3
33,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP124410.1,[6932368721519041699|+|9834685609301298901_1],768,segment_0,5
35,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP019012.1,[6932368721519041699|-|10145330714100251892_1],768,segment_0,1
5,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_LR890693.1,[6932368721519041699|-|11588582069103229002_1],768,segment_0,3
21,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_OX030701.1,[6932368721519041699|-|1314867519434933921_1],768,segment_0,4
48,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_AP022044.1,[6932368721519041699|-|14506298656834147691_1],768,segment_1,9
0,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP124455.1,[6932368721519041699|-|15558722379768673797_1],768,segment_0,7
1,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP107122.1,[6932368721519041699|-|15558722379768673797_1],768,segment_0,3
23,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP107162.1,[6932368721519041699|-|15558722379768673797_1],768,segment_0,6
44,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP107151.1,[6932368721519041699|-|15558722379768673797_1],768,segment_0,3
7,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP023826.1,[6932368721519041699|-|17115477248436968411_1],768,segment_0,4
20,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP018970.1,[6932368721519041699|-|17115477248436968411_1],768,segment_0,7
8,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP021454.1,[6932368721519041699|-|913783977968963568_1],768,segment_0,4
47,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP103562.1,[7844090243072536214|+|],1446,segment_0,2
31,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP124424.1,[964531385716605116|+|],1239,segment_0,2
2,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP128947.1,[964531385716605116|+|]_[16982887268023976258|+|],1863,segment_0,2
3,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP059130.1,[964531385716605116|+|]_[16982887268023976258|+|],1863,segment_1,2
4,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP124460.1,[964531385716605116|+|]_[16982887268023976258|+|],1863,segment_0,2
22,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP076693.1,[964531385716605116|+|]_[16982887268023976258|+|],1863,segment_0,2
25,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP036245.1,[964531385716605116|+|]_[16982887268023976258|+|],1863,segment_0,2
37,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_AP026794.1,[964531385716605116|+|]_[16982887268023976258|+|],1863,segment_0,2
38,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP027534.1,[964531385716605116|+|]_[16982887268023976258|+|],1863,segment_0,2
40,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_AP026788.1,[964531385716605116|+|]_[16982887268023976258|+|],1863,segment_0,2
6,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP010876.1,[964531385716605116|-|]_[16982887268023976258|-|],1863,segment_0,2
11,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_LR890693.1,[964531385716605116|-|]_[16982887268023976258|-|],1863,segment_1,2
43,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP124374.1,[964531385716605116|-|]_[16982887268023976258|-|],1863,segment_0,2
46,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP019015.1,[964531385716605116|-|]_[16982887268023976258|-|],1863,segment_0,2
50,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus2,NZ_AP022171.1,[18228278273347143766|+|],820,segment_0,2
49,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus2,NZ_CP098219.1,[2278011600046483881|+|],37622,segment_0,1

In [6]:
plasmid_insertions_df = find_insertion_hits_in_plasmids(plasmid_fasta_root="../results/plasmid_fastas", insertions_seq_dir=f"../results/atb_lookup/{example_junction}")

[M::mm_idx_gen::0.001*14.56] collected minimizers
[M::mm_idx_gen::0.002*8.81] sorted minimizers
[M::main::0.002*8.77] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.002*8.46] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.002*8.17] distinct minimizers: 415 (100.00% are singletons); average occurrences: 1.000; average spacing: 9.848; total length: 4087
[M::worker_pipeline::0.002*7.44] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/plasmid_fastas/NZ_CP124455.1/NZ_CP124458.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP124455.1_segment_0.fasta
[M::main] Real time: 0.002 sec; CPU: 0.014 sec; Peak RSS: 0.002 GB
[M::mm_idx_gen::0.001*13.50] collected minimizers
[M::mm_idx_gen::0.001*7.66] sorted minimizers
[M::main::0.001*7.63] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.001*7.40] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.001*7.18] distinct minimizers: 129 (100.00% are singletons); average occurrences: 1.000; average spacing: 10.124; total length: 1306
[M::worker_pipeline::0.001*6.45] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/plasmid_fastas/NZ_CP124455.1/NZ_CP124459.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP124455.1_segment_0.fasta
[M::main] Real time: 0.002 sec; CPU: 0.010 sec; Peak RSS: 0.002 GB
[M::mm_idx_gen::0.003*2.51] collected minimizers
[M::mm_idx_gen::0.006*2.70] sorted minimizers
[M::main::0.006*2.69] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.006*2.59] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.006*2.50] distinct minimizers: 13958 (96.86% are singletons); average occurrences: 1.051; average spacing: 9.985; total length: 146449
[M::worker_pipeline::0.007*2.43] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/plasmid_fastas/NZ_CP124455.1/NZ_CP124456.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP124455.1_segment_0.fasta
[M::main] Real time: 0.009 sec; CPU: 0.019 sec; Peak RSS: 0.004 GB
[M::mm_idx_gen::0.000*11.39] collected minimizers
[M::mm_idx_gen::0.001*7.05] sorted minimizers
[M::main::0.001*7.01] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.001*6.71] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.001*6.45] distinct minimizers: 512 (100.00% are singletons); average occurrences: 1.000; average spacing: 10.092; total length: 5167
[M::worker_pipeline::0.001*5.91] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/plasmid_fastas/NZ_CP124455.1/NZ_CP124457.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP124455.1_segment_0.fasta
[M::main] Real time: 0.001 sec; CPU: 0.007 sec; Peak RSS: 0.002 GB
[M::mm_idx_gen::0.001*5.16] collected minimizers
[M::mm_idx_gen::0.001*4.44] sorted minimizers
[M::main::0.001*4.43] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.001*4.35] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.002*4.26] distinct minimizers: 421 (100.00% are singletons); average occurrences: 1.000; average spacing: 9.696; total length: 4082
[M::worker_pipeline::0.002*4.07] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/plasmid_fastas/NZ_CP107122.1/NZ_CP107124.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP107122.1_segment_0.fasta
[M::main] Real time: 0.002 sec; CPU: 0.007 sec; Peak RSS: 0.002 GB
[M::mm_idx_gen::0.000*10.12] collected minimizers
[M::mm_idx_gen::0.001*6.44] sorted minimizers
[M::main::0.001*6.41] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.001*6.02] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.001*5.76] distinct minimizers: 188 (100.00% are singletons); average occurrences: 1.000; average spacing: 9.691; total length: 1822
[M::worker_pipeline::0.001*4.37] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/plasmid_fastas/NZ_CP107122.1/NZ_CP107125.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP107122.1_segment_0.fasta
[M::main] Real time: 0.001 sec; CPU: 0.006 sec; Peak RSS: 0.002 GB
[M::mm_idx_gen::0.003*2.13] collected minimizers
[M::mm_idx_gen::0.005*2.46] sorted minimizers
[M::main::0.005*2.46] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.006*2.38] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.006*2.31] distinct minimizers: 16241 (97.55% are singletons); average occurrences: 1.053; average spacing: 10.016; total length: 171301
[M::worker_pipeline::0.006*2.24] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/plasmid_fastas/NZ_CP107122.1/NZ_CP107123.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP107122.1_segment_0.fasta
[M::main] Real time: 0.008 sec; CPU: 0.016 sec; Peak RSS: 0.005 GB
[M::mm_idx_gen::0.000*10.15] collected minimizers
[M::mm_idx_gen::0.001*6.67] sorted minimizers
[M::main::0.001*6.64] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.001*6.39] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.001*6.18] distinct minimizers: 418 (100.00% are singletons); average occurrences: 1.000; average spacing: 9.778; total length: 4087
[M::worker_pipeline::0.001*5.60] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/plasmid_fastas/NZ_CP128947.1/NZ_CP128949.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP128947.1_segment_0.fasta
[M::main] Real time: 0.001 sec; CPU: 0.006 sec; Peak RSS: 0.002 GB
[M::mm_idx_gen::0.001*4.32] collected minimizers
[M::mm_idx_gen::0.002*3.73] sorted minimizers
[M::main::0.002*3.72] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.002*3.57] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.002*3.44] distinct minimizers: 3734 (97.13% are singletons); average occurrences: 1.056; average spacing: 9.922; total length: 39121
[M::worker_pipeline::0.002*3.31] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/plasmid_fastas/NZ_CP128947.1/NZ_CP128948.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP128947.1_segment_0.fasta
[M::main] Real time: 0.003 sec; CPU: 0.008 sec; Peak RSS: 0.003 GB
[M::mm_idx_gen::0.003*2.17] collected minimizers
[M::mm_idx_gen::0.005*2.44] sorted minimizers
[M::main::0.005*2.44] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.005*2.35] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.005*2.27] distinct minimizers: 15624 (95.41% are singletons); average occurrences: 1.074; average spacing: 9.999; total length: 167739
[M::worker_pipeline::0.006*2.25] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/plasmid_fastas/NZ_CP059130.1/NZ_CP059131.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP059130.1_segment_1.fasta
[M::main] Real time: 0.007 sec; CPU: 0.014 sec; Peak RSS: 0.005 GB
[M::mm_idx_gen::0.001*9.03] collected minimizers
[M::mm_idx_gen::0.001*6.64] sorted minimizers
[M::main::0.001*6.61] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.001*6.34] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.001*6.10] distinct minimizers: 413 (99.52% are singletons); average occurrences: 1.010; average spacing: 9.767; total length: 4073
[M::worker_pipeline::0.001*5.47] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/plasmid_fastas/NZ_CP059130.1/NZ_CP059132.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP059130.1_segment_1.fasta
[M::main] Real time: 0.001 sec; CPU: 0.006 sec; Peak RSS: 0.002 GB
[M::mm_idx_gen::0.000*11.08] collected minimizers
[M::mm_idx_gen::0.001*7.05] sorted minimizers
[M::main::0.001*7.03] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.001*6.82] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.001*6.62] distinct minimizers: 194 (100.00% are singletons); average occurrences: 1.000; average spacing: 10.830; total length: 2101
[M::worker_pipeline::0.001*5.90] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/plasmid_fastas/NZ_CP059130.1/NZ_CP059133.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP059130.1_segment_1.fasta
[M::main] Real time: 0.001 sec; CPU: 0.006 sec; Peak RSS: 0.002 GB
[M::mm_idx_gen::0.000*13.25] collected minimizers
[M::mm_idx_gen::0.001*7.51] sorted minimizers
[M::main::0.001*7.47] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.001*7.24] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.001*7.03] distinct minimizers: 142 (99.30% are singletons); average occurrences: 1.007; average spacing: 10.203; total length: 1459
[M::worker_pipeline::0.001*6.18] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/plasmid_fastas/NZ_CP059130.1/NZ_CP059134.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP059130.1_segment_1.fasta
[M::main] Real time: 0.001 sec; CPU: 0.006 sec; Peak RSS: 0.002 GB
[M::mm_idx_gen::0.001*9.14] collected minimizers
[M::mm_idx_gen::0.001*6.26] sorted minimizers
[M::main::0.001*6.25] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.001*5.96] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.001*5.70] distinct minimizers: 1236 (99.84% are singletons); average occurrences: 1.002; average spacing: 10.158; total length: 12575
[M::worker_pipeline::0.001*5.18] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/plasmid_fastas/NZ_CP124460.1/NZ_CP124464.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP124460.1_segment_0.fasta
[M::main] Real time: 0.001 sec; CPU: 0.007 sec; Peak RSS: 0.002 GB
[M::mm_idx_gen::0.000*9.88] collected minimizers
[M::mm_idx_gen::0.001*6.58] sorted minimizers
[M::main::0.001*6.56] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.001*6.32] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.001*6.10] distinct minimizers: 512 (100.00% are singletons); average occurrences: 1.000; average spacing: 10.092; total length: 5167
[M::worker_pipeline::0.001*5.46] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/plasmid_fastas/NZ_CP124460.1/NZ_CP124465.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP124460.1_segment_0.fasta
[M::main] Real time: 0.001 sec; CPU: 0.007 sec; Peak RSS: 0.002 GB
[M::mm_idx_gen::0.001*8.73] collected minimizers
[M::mm_idx_gen::0.001*6.06] sorted minimizers
[M::main::0.001*6.05] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.001*5.87] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.001*5.69] distinct minimizers: 420 (99.52% are singletons); average occurrences: 1.005; average spacing: 9.649; total length: 4072
[M::worker_pipeline::0.001*5.23] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/plasmid_fastas/NZ_CP124460.1/NZ_CP124466.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP124460.1_segment_0.fasta
[M::main] Real time: 0.001 sec; CPU: 0.006 sec; Peak RSS: 0.002 GB
[M::mm_idx_gen::0.001*4.35] collected minimizers
[M::mm_idx_gen::0.002*3.82] sorted minimizers
[M::main::0.002*3.81] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.002*3.66] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.002*3.52] distinct minimizers: 3480 (99.48% are singletons); average occurrences: 1.009; average spacing: 10.067; total length: 35356
[M::worker_pipeline::0.002*3.39] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/plasmid_fastas/NZ_CP124460.1/NZ_CP124463.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP124460.1_segment_0.fasta
[M::main] Real time: 0.003 sec; CPU: 0.008 sec; Peak RSS: 0.003 GB
[M::mm_idx_gen::0.002*3.24] collected minimizers
[M::mm_idx_gen::0.003*3.11] sorted minimizers
[M::main::0.003*3.11] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.004*2.98] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.004*2.86] distinct minimizers: 9534 (99.65% are singletons); average occurrences: 1.003; average spacing: 9.999; total length: 95665
[M::worker_pipeline::0.004*2.81] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/plasmid_fastas/NZ_CP124460.1/NZ_CP124462.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP124460.1_segment_0.fasta
[M::main] Real time: 0.005 sec; CPU: 0.013 sec; Peak RSS: 0.004 GB
[M::mm_idx_gen::0.002*3.55] collected minimizers
[M::mm_idx_gen::0.004*3.30] sorted minimizers
[M::main::0.004*3.30] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.004*3.15] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.004*3.03] distinct minimizers: 10609 (96.98% are singletons); average occurrences: 1.040; average spacing: 9.978; total length: 110076
[M::worker_pipeline::0.004*2.96] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/plasmid_fastas/NZ_CP124460.1/NZ_CP124461.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP124460.1_segment_0.fasta
[M::main] Real time: 0.006 sec; CPU: 0.015 sec; Peak RSS: 0.004 GB
[M::mm_idx_gen::0.001*4.28] collected minimizers
[M::mm_idx_gen::0.002*3.89] sorted minimizers
[M::main::0.002*3.89] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.002*3.82] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.002*3.75] distinct minimizers: 415 (100.00% are singletons); average occurrences: 1.000; average spacing: 9.793; total length: 4064
[M::worker_pipeline::0.002*3.61] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/plasmid_fastas/NZ_LR890693.1/NZ_LR890696.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_LR890693.1_segment_0.fasta
[M::main] Real time: 0.002 sec; CPU: 0.006 sec; Peak RSS: 0.002 GB
[M::mm_idx_gen::0.000*9.81] collected minimizers
[M::mm_idx_gen::0.001*6.83] sorted minimizers
[M::main::0.001*6.81] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.001*6.62] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.001*6.42] distinct minimizers: 161 (100.00% are singletons); average occurrences: 1.000; average spacing: 9.621; total length: 1549
[M::worker_pipeline::0.001*5.73] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/plasmid_fastas/NZ_LR890693.1/NZ_LR890697.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_LR890693.1_segment_0.fasta
[M::main] Real time: 0.001 sec; CPU: 0.006 sec; Peak RSS: 0.002 GB
[M::mm_idx_gen::0.000*11.93] collected minimizers
[M::mm_idx_gen::0.001*7.02] sorted minimizers
[M::main::0.001*7.00] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.001*6.72] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.001*6.30] distinct minimizers: 512 (100.00% are singletons); average occurrences: 1.000; average spacing: 10.092; total length: 5167
[M::worker_pipeline::0.001*5.70] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/plasmid_fastas/NZ_LR890693.1/NZ_LR890695.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_LR890693.1_segment_0.fasta
[M::main] Real time: 0.001 sec; CPU: 0.006 sec; Peak RSS: 0.002 GB
[M::mm_idx_gen::0.002*2.62] collected minimizers
[M::mm_idx_gen::0.004*2.71] sorted minimizers
[M::main::0.004*2.71] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.005*2.60] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.005*2.51] distinct minimizers: 11133 (98.18% are singletons); average occurrences: 1.024; average spacing: 9.894; total length: 112822
[M::worker_pipeline::0.005*2.46] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/plasmid_fastas/NZ_LR890693.1/NZ_LR890694.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_LR890693.1_segment_0.fasta
[M::main] Real time: 0.006 sec; CPU: 0.014 sec; Peak RSS: 0.004 GB
[M::mm_idx_gen::0.000*11.44] collected minimizers
[M::mm_idx_gen::0.001*6.92] sorted minimizers
[M::main::0.001*6.90] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.001*6.62] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.001*6.37] distinct minimizers: 513 (100.00% are singletons); average occurrences: 1.000; average spacing: 10.072; total length: 5167
[M::worker_pipeline::0.001*5.78] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/plasmid_fastas/NZ_CP010876.1/NZ_CP010879.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP010876.1_segment_0.fasta
[M::main] Real time: 0.001 sec; CPU: 0.006 sec; Peak RSS: 0.002 GB
[M::mm_idx_gen::0.000*12.17] collected minimizers
[M::mm_idx_gen::0.001*7.21] sorted minimizers
[M::main::0.001*7.18] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.001*6.89] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.001*6.63] distinct minimizers: 413 (100.00% are singletons); average occurrences: 1.000; average spacing: 9.898; total length: 4088
[M::worker_pipeline::0.001*6.03] mapped 1 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x asm5 -N 50 -p 0.9 -k 19 --eqx ../results/plasmid_fastas/NZ_CP010876.1/NZ_CP010878.1.fasta ../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/consensus1/NZ_CP010876.1_segment_0.fasta
[M::main] Real time: 0.001 sec; CPU: 0.006 sec; Peak RSS: 0.002 GB
[M::mm_idx_gen::0.001*4.58] collected minimizers
[M::mm_idx_gen::0.002*3.86] sorted minimizers
[M::main::0.002*3.85] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.002*3.70] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.002*3.56] distinct minimizers: 3062 (98.17% are singletons); average occurrences: 1.019; average spacing: 9.889; total length: 30855

In [7]:
plasmid_insertions_df

,junction_name,consensus,isolate_name,plasmid_name,insertion_path,insertion_length,segment,hits_in_plasmid
0,atb_lookup,consensus1,NZ_CP124455.1,NZ_CP124458.1,[6932368721519041699|-|15558722379768673797_1],768,segment_0,0
1,atb_lookup,consensus1,NZ_CP124455.1,NZ_CP124459.1,[6932368721519041699|-|15558722379768673797_1],768,segment_0,0
2,atb_lookup,consensus1,NZ_CP124455.1,NZ_CP124456.1,[6932368721519041699|-|15558722379768673797_1],768,segment_0,1
3,atb_lookup,consensus1,NZ_CP124455.1,NZ_CP124457.1,[6932368721519041699|-|15558722379768673797_1],768,segment_0,0
4,atb_lookup,consensus1,NZ_CP107122.1,NZ_CP107124.1,[6932368721519041699|-|15558722379768673797_1],768,segment_0,0
...,...,...,...,...,...,...,...,...
170,atb_lookup,consensus1,NZ_AP022044.1,NZ_AP022046.1,[6932368721519041699|-|14506298656834147691_1],768,segment_1,0
171,atb_lookup,consensus2,NZ_CP098219.1,NZ_CP098222.1,[2278011600046483881|+|],37622,segment_0,0
172,atb_lookup,consensus2,NZ_CP098219.1,NZ_CP098221.1,[2278011600046483881|+|],37622,segment_0,0
173,atb_lookup,consensus2,NZ_CP098219.1,NZ_CP098220.1,[2278011600046483881|+|],37622,segment_0,0
174,atb_lookup,consensus2,NZ_AP022171.1,NZ_AP022172.1,[18228278273347143766|+|],820,segment_0,0

In [9]:
plasmid_summary_df = plasmid_insertions_df.groupby(["consensus", "isolate_name", "segment"])["hits_in_plasmid"].sum().reset_index()
insertions_df = insertions_df.merge(
    plasmid_summary_df,
    left_on=["consensus", "genome_name", "segment"],
    right_on=["consensus", "isolate_name", "segment"],
    how="left"
).drop(columns=['isolate_name'])

insertions_df.sort_values(['consensus','insertion_path'])

,junction_name,consensus,genome_name,insertion_path,insertion_length,segment,hits_in_genome,hits_in_plasmid
27,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_AP026794.1,[16556873922195442803|+|],1661,segment_1,2,1
28,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_AP026788.1,[16556873922195442803|+|],1661,segment_1,2,1
9,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP124467.1,[185719230501067033|+|],4204,segment_0,1,0
29,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP134384.1,[185719230501067033|+|],4204,segment_0,1,0
36,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP133923.1,[185719230501067033|+|],4204,segment_0,1,0
41,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP019008.1,[185719230501067033|+|],4204,segment_0,1,0
12,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP021935.1,[517157241956952768|+|],1248,segment_0,3,0
13,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP107114.1,[517157241956952768|+|],1248,segment_0,5,0
14,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP107172.1,[517157241956952768|+|],1248,segment_0,2,0
18,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP059130.1,[517157241956952768|+|],1248,segment_0,4,0
19,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP021179.1,[517157241956952768|+|],1248,segment_0,7,0
10,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP124429.1,[517157241956952768|-|],1248,segment_0,6,0
16,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP018979.1,[517157241956952768|-|],1248,segment_0,2,0
15,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP051659.1,[6932368721519041699|+|10145330714100251892_1],768,segment_0,3,0
39,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP051661.1,[6932368721519041699|+|10145330714100251892_1],768,segment_1,4,1
17,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP107122.1,[6932368721519041699|+|11426489427845291638_1],768,segment_1,9,1
30,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP051661.1,[6932368721519041699|+|12883103544713419939_1],768,segment_0,4,1
34,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_AP022044.1,[6932368721519041699|+|12883103544713419939_1],768,segment_0,9,0
32,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP030337.1,[6932368721519041699|+|16056383497489254679_1],768,segment_0,3,0
26,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP128907.1,[6932368721519041699|+|1708810210093552769_1],768,segment_0,3,1
24,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_AP022326.1,[6932368721519041699|+|5100696243500885373_1],768,segment_0,4,1
42,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_AP022326.1,[6932368721519041699|+|6097212296783908714_1],768,segment_1,5,1
45,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP051663.1,[6932368721519041699|+|7987278316461198430_1],768,segment_0,3,1
33,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP124410.1,[6932368721519041699|+|9834685609301298901_1],768,segment_0,5,2
35,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP019012.1,[6932368721519041699|-|10145330714100251892_1],768,segment_0,1,0
5,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_LR890693.1,[6932368721519041699|-|11588582069103229002_1],768,segment_0,3,0
21,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_OX030701.1,[6932368721519041699|-|1314867519434933921_1],768,segment_0,4,3
48,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_AP022044.1,[6932368721519041699|-|14506298656834147691_1],768,segment_1,9,0
0,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP124455.1,[6932368721519041699|-|15558722379768673797_1],768,segment_0,7,1
1,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP107122.1,[6932368721519041699|-|15558722379768673797_1],768,segment_0,3,1
23,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP107162.1,[6932368721519041699|-|15558722379768673797_1],768,segment_0,6,2
44,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP107151.1,[6932368721519041699|-|15558722379768673797_1],768,segment_0,3,3
7,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP023826.1,[6932368721519041699|-|17115477248436968411_1],768,segment_0,4,2
20,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP018970.1,[6932368721519041699|-|17115477248436968411_1],768,segment_0,7,1
8,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP021454.1,[6932368721519041699|-|913783977968963568_1],768,segment_0,4,1
47,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP103562.1,[7844090243072536214|+|],1446,segment_0,2,0
31,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP124424.1,[964531385716605116|+|],1239,segment_0,2,1
2,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP128947.1,[964531385716605116|+|]_[16982887268023976258|+|],1863,segment_0,2,0
3,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP059130.1,[964531385716605116|+|]_[16982887268023976258|+|],1863,segment_1,2,0
4,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP124460.1,[964531385716605116|+|]_[16982887268023976258|+|],1863,segment_0,2,0
22,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP076693.1,[964531385716605116|+|]_[16982887268023976258|+|],1863,segment_0,2,0
25,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP036245.1,[964531385716605116|+|]_[16982887268023976258|+|],1863,segment_0,2,0
37,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_AP026794.1,[964531385716605116|+|]_[16982887268023976258|+|],1863,segment_0,2,0
38,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP027534.1,[964531385716605116|+|]_[16982887268023976258|+|],1863,segment_0,2,0
40,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_AP026788.1,[964531385716605116|+|]_[16982887268023976258|+|],1863,segment_0,2,0
6,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP010876.1,[964531385716605116|-|]_[16982887268023976258|-|],1863,segment_0,2,0
11,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_LR890693.1,[964531385716605116|-|]_[16982887268023976258|-|],1863,segment_1,2,0
43,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP124374.1,[964531385716605116|-|]_[16982887268023976258|-|],1863,segment_0,2,0
46,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus1,NZ_CP019015.1,[964531385716605116|-|]_[16982887268023976258|-|],1863,segment_0,2,0
50,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus2,NZ_AP022171.1,[18228278273347143766|+|],820,segment_0,2,0
49,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus2,NZ_CP098219.1,[2278011600046483881|+|],37622,segment_0,1,0

In [10]:
insertions_df.to_csv("../results/atb_lookup/CIRMBUYJFK_f__CWCCKOQCWZ_r/insertions_df.tsv", sep="\t", index=False)

In [7]:
load_all_deletions_summaries("../results/atb_lookup/deletions", example_junction, save_df=True)

,junction_name,consensus,genome_name,path,deletion,consensus_sequence,length,position,strand
0,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP018970.1,[13879318911159590194|+|]_[1145525430615568721...,deletion0,atgaaatcaatgtaactgtaatgaattttaatgatggtgccttttg...,6336,51236,+
1,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_AP022044.1,[11426489427845291638|+|]_[913783977968963568|...,deletion0,agggcgactattatggcccaatcggacgatgaatatgctgcagcgg...,1415,35766,+
2,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP019012.1,[12055620567302113403|+|],deletion0,caacatcccatttcgattattcctgtttcatttttgcttgccagtg...,2807,58505,+
3,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP134384.1,[12883103544713419939|+|]_[1158858206910322900...,deletion0,acagactttccctacttcgttgagagtacacctagtacaatcaagg...,1629,17382,+
4,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP019008.1,[12883103544713419939|+|]_[1158858206910322900...,deletion0,acagactttccctacttcgttgagagtacacctagtacaatcaagg...,1629,17382,+
5,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP051663.1,[5100696243500885373|+|]_[15395175763379073292...,deletion0,atgatgatttaacgagccataacaaaaccctgcctcggaggttttt...,37434,21143,+
6,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_AP026788.1,[6097212296783908714|+|],deletion0,agtaattaaactgatgtgtccctttactggcctggcgatagatacc...,302,61643,+
7,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP124467.1,[12883103544713419939|+|]_[1158858206910322900...,deletion0,acagactttccctacttcgttgagagtacacctagtacaatcaagg...,1629,17382,+
8,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP133923.1,[12883103544713419939|+|]_[1158858206910322900...,deletion0,acagactttccctacttcgttgagagtacacctagtacaatcaagg...,1629,17383,+
9,CIRMBUYJFK_f__CWCCKOQCWZ_r,consensus_1,NZ_CP128907.1,[17115477248436968411|+|]_[1387931891115959019...,deletion0,taagatttgccgtcactgatttgaaacggcggcagaaaacctgccg...,9704,48688,+